
const FoodData = [

    
    {
      id: 1,
      img: "https://images.pexels.com/photos/845812/pexels-photo-845812.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Onion Pizza",
      price: 150,
      desc: "A delicious pizza topped with fresh onions for a delightful flavor combination. This pizza is perfect for onion lovers and offers a unique twist on the classic pizza experience.",
      category: "Lunch",
      rating: 4.5,
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/18431672/pexels-photo-18431672/free-photo-of-pizza-margherita-cut-in-four.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Margherita Pizza",
      price: 130,
      desc: "A classic Italian pizza topped with fresh tomatoes, mozzarella cheese, basil leaves, and a drizzle of olive oil. Simple yet bursting with flavors, this Margherita Pizza is a timeless favorite that captures the essence of Italian cuisine.",
      category: "Lunch",
      rating: 4.2,
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/825661/pexels-photo-825661.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Pepperoni Pizza",
      price: 160,
      desc: "Indulge in the savory delight of this Pepperoni Pizza, loaded with slices of spicy pepperoni, melted cheese, and a tangy tomato sauce. A popular choice that's perfect for satisfying your pizza cravings.",
      category: "Lunch",
      rating: 4.6,
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/1552635/pexels-photo-1552635.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Mushroom and Spinach Pizza",
      price: 140,
      desc: "Experience the earthy flavors of mushrooms combined with the freshness of spinach on this delightful pizza. Topped with a blend of cheeses, this Mushroom and Spinach Pizza offers a balanced and satisfying taste.",
      category: "Lunch",
      rating: 4.2,
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/27562875/pexels-photo-27562875/free-photo-of-a-plate-of-chicken-wings-with-sauce-and-parsley.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "BBQ Chicken Pizza",
      price: 170,
      desc: "Savor the smoky goodness of this BBQ Chicken Pizza, featuring tender pieces of chicken marinated in barbecue sauce, red onions, and a medley of cheeses. A fusion of flavors that's sure to delight your taste buds.",
      category: "Lunch",
      rating: 4.8,
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Classic Pancakes",
      price: 80,
      desc: "Start your day with a stack of fluffy pancakes served with maple syrup and a dollop of butter. A timeless breakfast favorite that's sure to satisfy your morning cravings.",
      category: "Breakfast",
      rating: 4.5,
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/4109507/pexels-photo-4109507.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Egg and Bacon Croissant",
      price: 110,
      desc: "Indulge in a buttery croissant filled with scrambled eggs, crispy bacon, and melted cheese. A savory and satisfying breakfast option that's perfect for on-the-go mornings.",
      category: "Breakfast",
      rating: 4.2,
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/8743829/pexels-photo-8743829.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Greek Yogurt Parfait",
      price: 95,
      desc: "Enjoy a healthy and refreshing breakfast with layers of creamy Greek yogurt, fresh berries, honey, and granola. A balanced option that provides a burst of flavors and energy.",
      category: "Breakfast",
      rating: 4.1,
    },
    {
      id: 9,
      img: "https://images.pexels.com/photos/1351238/pexels-photo-1351238.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Avocado Toast",
      price: 120,
      desc: "Savor the creaminess of mashed avocado on toasted whole grain bread, topped with a sprinkle of sea salt and red pepper flakes. A trendy and nutritious breakfast choice.",
      category: "Breakfast",
      rating: 4.6,
    },
    {
      id: 10,
      img: "https://images.pexels.com/photos/7937332/pexels-photo-7937332.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Fruit and Nut Oatmeal",
      price: 85,
      desc: "Warm up with a bowl of hearty oatmeal packed with mixed fruits, nuts, and a drizzle of honey. A wholesome breakfast that provides a satisfying start to your day.",
      category: "Breakfast",
      rating: 4.5,
    },
    {
      id: 11,
      img: "https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Grilled Salmon",
      price: 190,
      desc: "Delight in a perfectly grilled salmon fillet seasoned with herbs and served with a side of roasted vegetables. A healthy and flavorful dinner option that's rich in omega-3 fatty acids.",
      category: "Dinner",
      rating: 4.5,
    },
    {
      id: 12,
      img: "https://images.pexels.com/photos/11220209/pexels-photo-11220209.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Chicken Alfredo Pasta",
      price: 160,
      desc: "Indulge in creamy fettuccine Alfredo pasta with tender pieces of grilled chicken. This comforting dinner dish is a blend of pasta, rich Alfredo sauce, and savory chicken.",
      category: "Dinner",
      rating: 4.8,
    },
    {
      id: 13,
      img: "https://images.pexels.com/photos/17321120/pexels-photo-17321120/free-photo-of-a-skillet-with-shrimp-and-peppers-on-it.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Vegetable Stir-Fry",
      price: 130,
      desc: "Enjoy a medley of colorful vegetables stir-fried in a flavorful sauce, served over steamed rice. A light and nutritious dinner that's both satisfying and wholesome.",
      category: "Dinner",
      rating: 4.2,
    },
    {
      id: 14,
      img: "https://images.pexels.com/photos/27819676/pexels-photo-27819676/free-photo-of-a-table-with-a-pizza-salad-and-other-food.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Grilled Chicken Burrito Bowl",
      price: 160,
      desc: "Savor the flavors of a delicious burrito bowl with tender grilled chicken, black beans, rice, sautéed peppers and onions, shredded cheese, and a drizzle of zesty cilantro-lime dressing. A hearty and satisfying chicken dinner option.",
      category: "Dinner",
      rating: 4.6,
    },
    {
      id: 15,
      img: "https://images.pexels.com/photos/21424385/pexels-photo-21424385/free-photo-of-top-view-of-a-mushroom-risotto-served-in-a-restaurant.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Mushroom Risotto",
      price: 175,
      desc: "Indulge in creamy and flavorful mushroom risotto, made with Arborio rice, sautéed mushrooms, and a touch of Parmesan cheese. A comforting and sophisticated dinner choice.",
      category: "Dinner",
      rating: 4.5,
    },
    {
      id: 16,
      img: "https://images.pexels.com/photos/6004791/pexels-photo-6004791.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Cheese and Crackers Platter",
      price: 120,
      desc: "Enjoy a variety of artisan cheeses, paired with an assortment of crispy crackers and complemented by fresh fruits and nuts. A delightful snack option for sharing or indulging in on your own.",
      category: "Snacks",
      rating: 4.3,
    },
    {
      id: 17,
      img: "https://images.pexels.com/photos/27645104/pexels-photo-27645104/free-photo-of-wild-wings-wings-photography.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Crispy Chicken Wings",
      price: 130,
      desc: "Savor the satisfying crunch of crispy chicken wings seasoned to perfection. Choose your favorite sauce, from tangy BBQ to spicy buffalo, for a flavorful snacking experience.",
      category: "Snacks",
      rating: 4.4,
    },
    {
      id: 18,
      img: "https://images.pexels.com/photos/3928854/pexels-photo-3928854.png?auto=compress&cs=tinysrgb&w=600",
      name: "Paneer Tikka Skewers",
      price: 130,
      desc: "Enjoy succulent pieces of marinated paneer (Indian cottage cheese) skewered and grilled to perfection. Served with mint chutney, these paneer tikka skewers offer a flavorful and aromatic Indian snack experience.",
      category: "Snacks",
      rating: 4.9,
    },
    {
      id: 19,
      img: "https://images.pexels.com/photos/27740559/pexels-photo-27740559/free-photo-of-a-buffet-of-food-with-bowls-of-soup-and-vegetables.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Hummus and Veggie Platter",
      price: 90,
      desc: "Relish the smooth and flavorful hummus accompanied by a variety of fresh vegetable sticks and pita bread. A nutritious and satisfying option for a light and refreshing snack.",
      category: "Snacks",
      rating: 4.4,
    },
    {
      id: 20,
      img: "https://images.pexels.com/photos/6861154/pexels-photo-6861154.jpeg?auto=compress&cs=tinysrgb&w=600",
      name: "Fruit Skewers",
      price: 70,
      desc: "Indulge in a colorful assortment of fruit skewers featuring juicy chunks of melon, berries, pineapple, and more. A sweet and refreshing snack that's both delicious and visually appealing.",
      category: "Snacks",
      rating: 4.8,
    },
  ];

export const AllCatogries = [
  {
     category : "All" , 
     img : "https://png.pngtree.com/background/20230528/original/pngtree-numerous-fast-food-items-sit-on-a-table-picture-image_2780284.jpg"
  },
    {
        category : "Lunch" , 
        img : "https://images.pexels.com/photos/90893/pexels-photo-90893.jpeg?auto=compress&cs=tinysrgb&w=600"
    },{
        category : "Breakfast" , 
        img : "https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&w=600"
    },{
        category : "Dinner" , 
        img : "https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg?auto=compress&cs=tinysrgb&w=600"
    },{
        category : "Snacks" , 
        img : "https://images.pexels.com/photos/298217/pexels-photo-298217.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
  ]
  export default FoodData  ;